version: '3.8'

services:
  remote-control:
    build: .
    container_name: remote-control-app
    ports:
      - "8765:8765"
    restart: unless-stopped
    environment:
      - PORT=8765

networks:
  default:
    driver: bridge